version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:123456@db:5432/es_quiz
    depends_on:
      - db
  db:
    container_name: pg_container
    image: postgres
#    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: es_quiz
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data:cached"
#      - "./postgres/postgresql.conf:/etc/postgresql.conf"
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
