version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:123456@db:5432/es_quiz
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis-cache
  db:
    container_name: pg_container
    image: postgres
#    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: es_quiz
    ports:
      - "5433:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data:cached"
  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - cache:/data